variables:
  IMAGE_NAME: registry.digitwalk.com/yobot

stages:
  - build
  - push
  - deploy
  - cleanup

build_production:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:dist .
  only:
    - master
  tags:
    - build

push_production:
  stage: push
  script:
    - docker push $IMAGE_NAME:dist
  only:
    - master
  tags:
    - push

deploy_production:
  stage: deploy
  script:
    - docker-compose -f production.yml pull
    - docker-compose -f production.yml up -d
  only:
    - master
  tags:
    - production

cleanup_production:
  stage: cleanup
  script:
    - EMPTYIMAGE=$(docker images | awk '{print $1, $3}' | grep '^<none>' | awk '{print $2}') sh -c 'if [ ! -z "$EMPTYIMAGE" ]; then docker rmi $EMPTYIMAGE; fi'
  only:
    - master
  tags:
    - production
  allow_failure: true
